### ISSUE TITLE
CUDA error at /home/xiluo/Scalable-Neural-Indoor-Scene-Rendering/rendering/src/render_to_screen.cpp:144 code=101(cudaErrorInvalidDevice) "cudaGraphicsGLRegisterBuffer(&cuda_pbo_resource, pbo, cudaGraphicsMapFlagsWriteDiscard)" 

### ISSUE THREAD

**Issue by xiluoxiluo** [XchaoWu/Scalable-Neural-Indoor-Scene-Rendering#5]
Hello, thank you for this bright project.

When I am trying to run demo.sh script I face the following errors :
`CUDA error at /home/xiluo/Scalable-Neural-Indoor-Scene-Rendering/rendering/src/render_to_screen.cpp:144 code=101(cudaErrorInvalidDevice) "cudaGraphicsGLRegisterBuffer(&cuda_pbo_resource, pbo, cudaGraphicsMapFlagsWriteDiscard)" `
How can I fix that? Can you please help me with that?
My CUDA version is 11.3
GCC version is 7.5
Ubuntu 20.04

Thank you in advance.

**Comment by XchaoWu** [comment]
Maybe you can try CUDA version 11.1?

**Comment by xiluoxiluo** [comment]
Thank you for your reply @XchaoWu . I later found that this error was caused by the index error of multiple GPUs on my server. I unplugged the rest of the GPUs and kept only one GPU. This problem was solved. Thank you again!
